version: '3.8'

services:
  app:
    image: spring-demo-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    volumes:
      - ./:/app
      - ./gradle/container/:/root/.gradle
      - gradle:/home/gradle/
    working_dir: /app
    entrypoint: gradle  --debug --stacktrace --scan bootRun
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: automobiles

volumes:
  postgres_data:
  gradle:
